/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.zhongkk.service.rpc;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface AddService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"AddService\",\"namespace\":\"com.zhongkk.service.rpc\",\"types\":[],\"messages\":{\"add\":{\"request\":[{\"name\":\"i\",\"type\":\"int\"},{\"name\":\"j\",\"type\":\"int\"}],\"response\":\"int\"}}}");
  int add(int i, int j) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends AddService {
    public static final org.apache.avro.Protocol PROTOCOL = com.zhongkk.service.rpc.AddService.PROTOCOL;
    void add(int i, int j, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
  }
}